/*******************************************************************************
 * This program answers the question: push n distinct integers from 0 to n-1 in
 * order onto a stack, and intermix pop operation in the push sequence, can the
 * stack be used to generate a given permutation of these numbers?
 *
 * Pattern 312 cannot be generated by a single stack.
 * for a[i], a[i+1], a[i+2],
 * if a[i] > a[i+2] > a[i+1], then it is pattern 312.
 *
 * This program can also generate the operation sequence that is used to
 * generate the generable target permutation.
 *
 * Sample execution:
 *
 * $ java-algs4 StackPermutable < stack_permutable_in
 * (4 3 2 1 0 9 8 7 6 5) can be generated by a stack? true
 * +++++-----+++++-----
 * (4 3 2 1 0 9 8 7 6 5) is generated using the above operation sequence.
 *
 * (4 6 8 7 5 3 2 9 0 1) can be generated by a stack? false
 *
 * (2 0 1) can be generated by a stack? false
 *
 * (0 1 2) can be generated by a stack? true
 * +-+-+-
 * (0 1 2) is generated using the above operation sequence.
 *
 * @author Ryan Duan <duanpanda@gmail.com>
 ******************************************************************************/

import edu.princeton.cs.algs4.Stack;

public class StackPermutable {

    /**
     * Can a stack generate the given sequence by inputting int 0 to n-1?
     *  runtime complexity: O(n)
     *  pattern 312 cannot be generated by a single stack
     * TODO: need to be tested by all permutations. It may need O(n^3).
     */
    public static boolean canGenerate(int[] a) {
        for (int i = 0; i < a.length - 2; i++) {
            if (a[i] > a[i+2] && a[i+2] > a[i+1]) {
                return false;
            }
        }
        return true;
    }

    /**
     * If a stack can generate the target sequence by inputting int 0 to n-1,
     * then this method can get the generator which is an intermixed sequence
     * of stack push and pop operations.  The returned value is a string
     * sequence in which "+" denotes a push and "-" denotes a pop.
     *
     * @throws RuntimeException if the target sequence cannot be generated by a
     * single stack.
     */
    public static String getGenerator(int[] target) {
        if (target.length == 0)
            return null;

        StringBuilder ops = new StringBuilder(target.length * 2);
        Stack<Integer> stack = new Stack<Integer>();
        int i = 0;              // target array index
        int j = 0;              // 0 to n-1 input sequence iterator
        stack.push(j);
        ops.append('+');
        for (i = 0; i < target.length; i++) {
            while (stack.isEmpty() || target[i] > stack.peek()) {
                stack.push(++j);
                ops.append('+');
            }
            if (target[i] == stack.peek()) {
                stack.pop();
                ops.append('-');
            }
            else {
                throw new RuntimeException("cannot be generated");
            }
        }
        return ops.toString();
    }

    /**
     * Using the generator (a push and pop sequence) and inputting 0, 1, 2, ...
     * to generate a permutation of the input numbers.
     */
    public static int[] generate(String generator) {
        int i = 0;              // next integer to be put int the result
        Stack<Integer> stack = new Stack<Integer>();
        int[] result = new int[generator.length() / 2];
        int j = 0;              // index for result[]
        for (int k = 0; k < generator.length(); k++) {
            if (generator.charAt(k) == '+') {
                stack.push(i);
                i++;
            }
            else if (generator.charAt(k) == '-') {
                result[j++] = stack.pop();
            }
        }
        return result;
    }

    private static void printIntList(int[] a) {
        StdOut.print("(");
        int i;
        for (i = 0; i < a.length - 1; i++) {
            StdOut.print(a[i] + " ");
        }
        StdOut.print(a[i] + ")");
    }

    public static void main(String[] args) {
        while (!StdIn.isEmpty()) {
            int n = StdIn.readInt();
            int[] a = new int[n];
            for (int i = 0; i < n; i++) {
                a[i] = StdIn.readInt();
            }

            printIntList(a);
            boolean canGen = canGenerate(a);
            StdOut.println(" can be generated by a stack? " + canGen);

            // if (canGen) {
            //     String opseq = getGenerator(a);
            //     StdOut.println(opseq);
            //     printIntList(generate(opseq));
            //     StdOut.println(" is generated using the above operation sequence.");
            // }
            StdOut.print("Trying to generate it ...");
            try {
                String opseq = getGenerator(a);
                StdOut.println();
                StdOut.println(opseq);

                printIntList(generate(opseq));
                StdOut.println(" is generated using the above operation sequence.");
            }
            catch (RuntimeException e) {
                StdOut.println("Oops, you are right, it cannot be generated.");
            }
            StdOut.println();
        }
    }
}
